### ISSUE TITLE
Use of archives instead of deb packages

### ISSUE THREAD

**Issue by jakobjakobson13** [flathub/com.elsevier.MendeleyDesktop#30]
Dear developers,

wouldn't it be easier to use the mendeley packages instead of the debian packages? The corresponding code would look like this

```
    sources:
    - only-arches: [i386]
      type: archive
      url: https://desktop-download.mendeley.com/download/linux/mendeleydesktop-1.19.4-linux-i486.tar.bz2
      sha256: 00e8047d1c2cb71db7ded001841e95d37415c72884403bdcb24bb99895f090d3
      x-checker-data:
	type: rotating-url
	url: https://www.mendeley.com/autoupdates/installer/Linux-x86/stable-incoming
    - only-arches: [x86_64]
      type: archive
      url: https://desktop-download.mendeley.com/download/linux/mendeleydesktop-1.19.4-linux-x86_64.tar.bz2
      sha256: 9700f2db273bb364aadb92535ba40349626193e0ba5ff8544ce22b665d5d7dd9
      x-checker-data:
	type: rotating-url
	url: https://www.mendeley.com/autoupdates/installer/Linux-x64/stable-incoming
```
